config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'
  resources :restaurants
  resources :restaurant_types
  devise_for :users

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :restaurant_type
  belongs_to :user
end

app/models/restaurant_type.rb
class RestaurantType < ActiveRecord::Base

  has_many :restaurants

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :restaurants
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_action :authenticate_user!
  def index
    @restaurants = Restaurant.all.order(:name)
  end
end

app/controllers/restaurant_types_controller.rb
class RestaurantTypesController < ApplicationController
  before_action :set_restaurant_type, only: [:show, :edit, :update, :destroy]

  # GET /restaurant_types
  # GET /restaurant_types.json
  def index
    @restaurant_types = RestaurantType.all
  end

  # GET /restaurant_types/1
  # GET /restaurant_types/1.json
  def show
  end

  # GET /restaurant_types/new
  def new
    @restaurant_type = RestaurantType.new
  end

  # GET /restaurant_types/1/edit
  def edit
  end

  # POST /restaurant_types
  # POST /restaurant_types.json
  def create
    @restaurant_type = RestaurantType.new(restaurant_type_params)

    respond_to do |format|
      if @restaurant_type.save
        format.html { redirect_to @restaurant_type, notice: 'Restaurant type was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant_type }
      else
        format.html { render :new }
        format.json { render json: @restaurant_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurant_types/1
  # PATCH/PUT /restaurant_types/1.json
  def update
    respond_to do |format|
      if @restaurant_type.update(restaurant_type_params)
        format.html { redirect_to @restaurant_type, notice: 'Restaurant type was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant_type }
      else
        format.html { render :edit }
        format.json { render json: @restaurant_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurant_types/1
  # DELETE /restaurant_types/1.json
  def destroy
    @restaurant_type.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_types_url, notice: 'Restaurant type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant_type
      @restaurant_type = RestaurantType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_type_params
      params.require(:restaurant_type).permit(:name)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :postcode, :suburb, :restaurant_type_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurant_types_helper.rb
module RestaurantTypesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/home/index.html.erb
<h1>Menulog</h1>

<% @restaurants.each do |restaurant| %>
<div class="panel">
  <div class="panel-header">
    <h3><%= restaurant.name %></h3>
  </div>
  <div class="panel-body">
    <p>
      <%= restaurant.description %>
    </p>

      <%= link_to restaurant.name, restaurant_path(restaurant), class: 'btn btn-info' %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Menulog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class="container">
    <%= yield %>
  </div>
</div>


</body>
</html>

app/views/restaurant_types/_form.html.erb
<%= simple_form_for(@restaurant_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurant_types/edit.html.erb
<h1>Editing Restaurant Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant_type %> |
<%= link_to 'Back', restaurant_types_path %>

app/views/restaurant_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restaurant Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurant_types.each do |restaurant_type| %>
      <tr>
        <td><%= restaurant_type.name %></td>
        <td><%= link_to 'Show', restaurant_type %></td>
        <td><%= link_to 'Edit', edit_restaurant_type_path(restaurant_type) %></td>
        <td><%= link_to 'Destroy', restaurant_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant type', new_restaurant_type_path %>

app/views/restaurant_types/new.html.erb
<h1>New Restaurant Type</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurant_types_path %>

app/views/restaurant_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant_type.name %>
</p>

<%= link_to 'Edit', edit_restaurant_type_path(@restaurant_type) %> |
<%= link_to 'Back', restaurant_types_path %>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :postcode %>
    <%= f.input :suburb %>
    <%= f.association :restaurant_type %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="container">
<h1>Listing Restaurants</h1>


<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Address</th>
      <th>Postcode</th>
      <th>Suburb</th>
      <th>Restaurant type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.description %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.postcode %></td>
        <td><%= restaurant.suburb %></td>
        <td><%= restaurant.restaurant_type.name %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New Restaurant', new_restaurant_path %>
</div>
</div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @restaurant.postcode %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @restaurant.suburb %>
</p>

<p>
  <strong>Restaurant type:</strong>
  <%= @restaurant.restaurant_type.name %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>